#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on 23/04/2024 21:31:45

@author: psakic
"""

import datetime as dt
import glob
import itertools
import logging
import os
import pathlib
import re

import pandas as pd

from . import download_utils as dlutils
from geodezyx import conv

log = logging.getLogger("geodezyx")

from .servers_rinex import _server_select_rnx


def download_gnss_rinex(
    statdico,
    output_dir,
    startdate,
    enddate,
    archtype="year/doy",
    parallel_download=4,
    user="anonymous",
    passwd="anonymous@isp.com",
    path_ftp_crawled_files_save=None,
    path_ftp_crawled_files_load=None,
    skip_crawl=False,
    path_all_ftp_files_save=None,
    quiet_mode=False,
    final_archive_for_sup_check=None,
    force=False,
    no_rnx2=False,
    no_rnx3=False,
    intuitive_output=False,
):
    """
    Parameters
    ----------
    statdico : dict
        a statdico is a dictionary associating Archives Centers to list of stations

        Exemple:
            >>> statdico['archive center 1'] = ['STA1','STA200XXX','STA3', ...]
            >>> statdico['archive center 2'] = ['STA200XXX','STA1','STA4', ...]

        the supported archive center are (april 2024):
            * igs_cddis or igs (CDDIS data center)
            * igs_sopac (for the SOPAC/UCSD/SIO data center, but not very reliable)
            * igs_ign (IGN's data center, main server at St Mandé)
            * igs_ign_ensg (IGN's data center, secondary server at ENSG, Marne-la-Vallée)
            * igs_bkg (BKG's IGS data center, for the IGS stations)
            * sonel
            * euref (EPN data center hosted at ROB)
            * nav or brdc as archive center allows to download nav files (using 'BRDC' as station name)
            * from the ROB server, using GOP files
            * nav_rt or brdc_rt as archive center allows to download *real time* nav files from the BKG server
            * rgp (IGN's RGP main server at St Mandé)
            * rgp_ensg (IGN's RGP, secondary server at ENSG, Marne-la-Vallée)
            * rgp_v3 (IGN's RGP main server at St Mandé - RINEX3)
            * rgp_ensg_v3 (IGN's RGP, secondary server at ENSG, Marne-la-Vallée - RINEX3)
            * rgp_01s (IGN's RGP, all the 24 hourly rinex for the day will be downloaded)
            * renag
            * renag_crtk & renag_crtk_01s (Centipede RTK data hosted at RENAG)
            * ovsg
            * unavco
            * geoaus (Geosciences Australia)
            * ens_fr

    output_dir : str
        the root directory on your local drive were to store the RINEXs

    archtype : str
        string describing how the archive directory is structured, e.g:
            * stat
            * stat/year
            * stat/year/doy
            * year/doy
            * year/stat
            * week/dow/stat
            * etc ...

    user & passwd : str
        user & password for a secure server

    path_ftp_crawled_files_save : str
        will save at the given path (directory+filename) in a CSV file containing
        the list of the existing RINEXs found on the server by the FTP crawler.
        It allows to use this list directly if one face a timeout during
        the download part.

    path_ftp_crawled_files_load : str
        load and use the list of the existing RINEXs found on the FTP server,
        generated by a previous run of the FTP crawler (called by
        download_gnss_rinex or directly by crawl_ftp_files).
        a new call of crawl_ftp_files can be bypassed with
        `skip_crawl`.

    skip_crawl : bool
        when a list of the existing RINEXs found on the FTP server
        is provided with path_ftp_crawled_files_load, skip
        a new call of crawl_ftp_files.
        Then, we assume the provided list as a complete one,
        ready for the download step

    path_all_ftp_files_save : str
        will save at the given path (directory+filename) in a CSV file
        ALL the remote files found on the FTP server.
        NB: CSV file will be saved each time a new FTP instance
        is created, i.e. every 50 days

    quiet_mode : bool
        List the available RINEXs without downloading them.
        Useful only if path_ftp_crawled_files_save is given

    final_archive_for_sup_check : str
        The final archive path or a file containing the archived RINEXs in
        their final destination.
        useful if the final archive is different from archive_dir
        *** not re-implemented yet ***

    force : bool
        Force the download even if the file already exists locally

    no_rnx2 & no_rnx3 : bool
        limit the search/download to RINEX2 (short names) and/or
        RINEX3 (long names) depending on the boolean given

    Returns
    -------
    out_tup_lis : List of tuples
        Returns a list of tuples containing
        the local path of the downloaded file and
        a boolean indicating whether the download was successful.
        e.g. [(local_path1, True), (local_path2, False), ...]
        NB: files that already exist locally are marked
        as (local_path, True)

    Minimal exemple
    ---------------
    .. code-block:: python

        >>> statdic = dict()
        >>> statdic['igs_cddis'] = ['ZIMM','tlse']
        >>> archive_dir = '/home/USER/test_dl_rnx'
        >>> startdate = dt.datetime(2020,1,1)
        >>> enddate = dt.datetime(2020,1,31)
        >>> geodezyx.operational.download_gnss_rinex(statdic, output_dir, startdate, enddate)
    """

    if "01s" in list(statdico.keys())[0]:
        day_step, sec_step, rnd = 0, 3600, "1h"
    else:
        day_step, sec_step, rnd = 1, 0, "1d"

    startdate_use = conv.round_dt(startdate, rnd)
    enddate_use = conv.round_dt(enddate, rnd)

    date_range = conv.dt_range(
        startdate_use, enddate_use, day_step=day_step, sec_step=sec_step
    )
    log.info("dates: %s to %s", startdate_use, enddate_use)

    if path_ftp_crawled_files_load:
        table_ini = pd.read_csv(path_ftp_crawled_files_load)
    else:
        table_ini = gen_table_rnx(
            statdico, date_range, output_dir, archtype, no_rnx2, no_rnx3
        )

    if len(table_ini) == 0:
        log.error("No RINEX files found for the given criteria.")
        return None

    if skip_crawl:
        table_crawl = table_ini
        files_all = pd.Series([], dtype=str)
        files_loc = pd.Series([], dtype=str)
    else:
        table_crawl, files_all, files_loc = dlutils.crawl_ftp_files(
            table_ini,
            sftp="auto",
            user=user,
            passwd=passwd,
            path_ftp_crawled_files_save=path_ftp_crawled_files_save,
            path_all_ftp_files_save=path_all_ftp_files_save,
            force=force,
        )

    #### get only the valid (true) url
    table_dwld = table_crawl.loc[table_crawl["url_true"].dropna().index]

    # Initialize output list
    out_tup_lis = []

    # Only download if files are available and not in quiet mode
    if len(table_dwld) == 0:
        errmsg = (
            "no valid RINEX URL found/selected on the FTP server, check your inputs"
        )
        log.error(errmsg)
    elif quiet_mode:
        log.warning("quiet mode, no download was performed")
    else:
        out_tup_lis = dlutils.ftp_downld_front(
            table_dwld["url_true"].values,
            table_dwld["outdir"].values,
            parallel_download=parallel_download,
            secure_ftp=(table_dwld["protocol"] == "sftp").values,
            user=user,
            passwd=passwd,
            force=force,
        )

    ### add the local paths to the output tuples
    if len(files_loc) > 0:
        loc_tup_lis = [(f, True) for f in files_loc]
        out_tup_lis_fin = loc_tup_lis + out_tup_lis
    else:
        out_tup_lis_fin = out_tup_lis

    log.info(
        "RINEX files fetched: total: %d, downloaded: %d, already here: %d",
        len(out_tup_lis_fin),
        len(out_tup_lis),
        len(files_loc),
    )

    if not intuitive_output:
        return out_tup_lis_fin
    else:
        return zip(*out_tup_lis_fin)


def gen_table_rnx(
    statdico,
    date_range,
    output_dir,
    archtype,
    no_rnx2,
    no_rnx3,
):
    """
    Generate a crawl table for RINEX file downloads.

    Parameters
    ----------
    statdico : dict
        Dictionary mapping data centers to station lists.
    date_range : list
        List of datetime objects for the date range.
    output_dir : str
        Root output directory.
    archtype : str
        Archive directory structure type.
    no_rnx2 : bool
        Skip RINEX2 files if True.
    no_rnx3 : bool
        Skip RINEX3 files if True.

    Returns
    -------
    pd.DataFrame
        Table with download metadata for each RINEX file.
    """
    table_proto = []

    all_sites = False
    for datacenter, site_lis in statdico.items():
        if site_lis is None:
            site_lis = [None]
            log.info("datacenter/stations: %s/all", datacenter)
        else:
            log.info("datacenter/stations: %s/%s", datacenter, " ".join(site_lis))
        for site, date in itertools.product(site_lis, date_range):
            if site is None:
                all_sites = True

            urldic, protocol, _ = _server_select_rnx(datacenter, date, site)
            if not urldic:
                continue

            outdir = dlutils.effective_save_dir(output_dir, site, date, archtype)

            for rnxver, rnxurl in urldic.items():
                if (rnxver == 2 and no_rnx2) or (rnxver == 3 and no_rnx3):
                    continue
                table_proto.append((date, site, outdir, rnxver, rnxurl, protocol))

    cols = ["date", "site", "outdir", "ver", "url_theo", "protocol"]
    # Create DataFrame with all collected data
    table = pd.DataFrame(table_proto, columns=cols)

    # Add status columns
    table["crawled"] = False
    table["ok_dwl"] = False
    table["ok_loc"] = False
    table["all"] = all_sites
    table["url_true"] = None
    table["filename"] = ""

    # Parse URL components
    urlpaths = table["url_theo"].apply(pathlib.Path)
    table["regex"] = urlpaths.apply(lambda p: p.name)
    table["host"] = urlpaths.apply(lambda p: p.parts[1])
    table["dir"] = urlpaths.apply(lambda p: os.path.join(*p.parts[2:-1]))

    # Sort table to ensure consistent order
    table.sort_values(by=["site", "date"], inplace=True)
    table.reset_index(drop=True, inplace=True)


    log.info(table.to_string())

    return table
